CREATE ROLE cartowner WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOREPLICATION
  PASSWORD 'XXXXXXXX';

GRANT cartowner TO postgres;
  
CREATE ROLE cartuser WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  PASSWORD 'XXXXXXXX';
  
CREATE SCHEMA cart
    AUTHORIZATION cartowner;

GRANT ALL ON SCHEMA cart TO cartowner;

GRANT USAGE ON SCHEMA cart TO cartuser;
 
ALTER ROLE cartowner NOSUPERUSER CREATEDB NOCREATEROLE INHERIT LOGIN NOREPLICATION NOBYPASSRLS;
 